trigger: none

# This will not cause triggers in Azure Repos git, for that you need a branch policy
# But it will trigger for other source code repos, like GitHub
pr:
  paths:
    include:
      - aml
      - model
      - .pipelines/pr-model.yml
      - .pipelines/templates/template-python-code-validation.yml
      - .pipelines/templates/template-model-validation.yml

variables:
  - name: pythonVersion
    value: '3.8'
  - name: modelRegexIncludeFilter
    value: 'model\/.*'
  - name: modelWorkingDir
    value: '$(Build.SourcesDirectory)/model'
  - name: amlRegexIncludeFilter
    value: 'aml\/.*'
  - name: amlWorkingDir
    value: '$(Build.SourcesDirectory)/aml'

pool:
  vmImage: 'ubuntu-20.04'

jobs:
  - job: model_code_validation_job
    displayName: 'Run model code validation tests'
    steps:
      - template: templates/template-model-validation.yml
        parameters:
          pythonVersion: $(pythonVersion)
          regexIncludeFilter: $(modelRegexIncludeFilter)
          workingDir: $(modelWorkingDir)

  - job: aml_code_validation_job
    displayName: 'Run AML python code validation tests'
    steps:
      - template: templates/template-python-code-validation.yml
        parameters:
          pythonVersion: $(pythonVersion)
          regexIncludeFilter: $(amlRegexIncludeFilter)
          reportPrefix: 'aml'
          workingDir: $(amlWorkingDir)
