# publish azureml_appinsights_logger
pr: none

resources:
  pipelines:
  - pipeline: observability_lib_ci
    source: observability-lib-ci
    trigger:
      branches:
        include:
        - main

stages:
- stage: download_build_artifacts
  pool:
    vmImage: ubuntu-latest
  jobs:
    - job: download_package

      steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'specific'
          project: '$(System.TeamProjectId)'
          pipelineId: 44
          specificBuildWithTriggering: true
          buildVersionToDownload: 'latest'
          branchName: 'main'
          artifactName: 'observability_lib_whl'
          targetPath: '$(Pipeline.Workspace)'

- stage: publish_to_ado_feed
  pool:
    vmImage: ubuntu-latest
  jobs:
  - deployment: publish_to_ado_feed
    environment: 'publish_to_pypi_env'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
            displayName: 'Use Python 3.x'

          - script: |
              pip install twine
            displayName: 'install twine'

          - task: TwineAuthenticate@1
            inputs:
              artifactFeed: 'MLOpsManufacturing/observability_feed'

          - script: |
              ls $(Pipeline.Workspace)
            displayName: 'list folder'

          - script: |
              python -m twine upload -r observability_feed --config-file $(PYPIRC_PATH) $(Pipeline.Workspace)/dist
            displayName: 'publish to ADO feed'
