# For build validation of custom preprocessing aml pipeline step compatible Dockerfile
pr:
  branches:
    include:
    - main
  paths:
    include:
    - samples/non-python-preprocess/ml_model/preprocessing/Dockerfile
    
jobs:
  - job: buildAmlPipelineCompContainer
    displayName: 'Docker build validation aml pipeline compatible step'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: docker build -f Dockerfile .
      workingDirectory: $(Build.SourcesDirectory)/ml_model/preprocessing/
      displayName: 'Docker build validation aml pipeline compatible step'
