# Continuous Integration (CI) pipeline that orchestrates the training, evaluation, and registration of the model.
parameters:
  - name: aml_pipeline_name
    displayName: AML Pipeline Name to trigger
    type: string
    default: flower-preprocessing-pipeline
  - name: workingDirectory
    displayName: Working Directory for sample
    type: string
    default: samples/image-classification-tensorflow

resources:
  containers:
  - container: mlops
    image: mlopsmanufacturing/build-agent/tensorflow:build-20201203.1
    endpoint: mlopsmanufacturingacr

pr: none
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - samples/image-classification-tensorflow/ml_model/preprocessing/
    - samples/image-classification-tensorflow/ml_model/parameters.json
    - samples/image-classification-tensorflow/ml_service/pipelines/build_data_processing_pipeline.py
    - samples/image-classification-tensorflow/.pipelines/02-processing-data.yml
    - samples/image-classification-tensorflow/.pipelines/variables-template.yml
    - samples/image-classification-tensorflow/.pipelines/code-quality-template.yml
    - samples/image-classification-tensorflow/.pipelines/trigger-preprocessing-pipeline.yml


variables:
- template: variables-template.yml
- group: devopsforai-aml-vg

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Data_CI'
  displayName: 'Data code quality and publish preprocessing pipeline'
  jobs:
  - job: "Data_CI_Pipeline"
    displayName: "Data CI Pipeline"
    container: mlops
    timeoutInMinutes: 0
    steps:
    - template: code-quality-template.yml
      parameters:
        workingDirectory: ${{ parameters.workingDirectory }}
    - task: AzureCLI@1
      enabled: true
      inputs:
        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
        scriptLocation: inlineScript
        workingDirectory: ${{ parameters.workingDirectory }}
        inlineScript: |
          set -e # fail on error
          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          # Invoke the Python building and publishing a data preprocessing pipeline
          python -m ml_service.pipelines.build_data_processing_pipeline
      displayName: 'Publish Data Preprocessing Pipeline'

# Trigger_Preprocessing_Pipeline
- template: trigger-preprocessing-pipeline.yml
  parameters:
    # Template parameters can not be expanded, hard coded here
    aml_pipeline_name: ${{ parameters.aml_pipeline_name }}
    workingDirectory: ${{ parameters.workingDirectory }}
    # aml_pipeline_name: ${{ variable.PREPROCESSING_PIPELINE_NAME }}
    # aml_pipeline_name: $(PREPROCESSING_PIPELINE_NAME)
    # Variable expanding for Parameters is not always possible:
    # https://developercommunity.visualstudio.com/content/problem/429990/azure-pipelines-passing-a-variable-as-a-parameter.html