# Pipeline for building the container image that is used by other pipelines for scoring.
parameters:
- name : artifactBuildId
  displayName: Model Train CI Build ID. Default is 'latest'.
  type: string
  default: latest
- name: workingDirectory
  displayName: Working Directory for sample
  type: string
  default: samples/image-classification-tensorflow

resources:
  containers:
  - container: mlops
    image: mlopsmanufacturing/build-agent/tensorflow:latest
    endpoint: mlopsmanufacturingacr
  pipelines:
  - pipeline: model-train-ci
    source: 03-train-evaluate-register-model # Name of the triggering pipeline
  - pipeline: model-test-deploy-ci
    source: 04-deploy-model-aci # Name of the triggering pipeline
    trigger:
      branches:
        include:
        - main

pr: none
trigger: none

pool: 
  vmImage: 'ubuntu-latest'

container: mlops

variables:
- template: variables-template.yml
- group: devopsforai-aml-vg

steps:
- template: get-model-id-artifact-template.yml
  parameters:
    projectId: '$(resources.pipeline.model-train-ci.projectID)'
    pipelineId: '$(resources.pipeline.model-train-ci.pipelineID)'
    artifactBuildId: ${{ parameters.artifactBuildId }}
- template: package-model-template.yml
  parameters:
    modelId: $(MODEL_NAME):$(get_model.MODEL_VERSION)
    scoringScriptPath: '$(Build.SourcesDirectory)/$(SOURCES_DIR_TRAIN)/scoring/score.py'
    condaFilePath: '$(Build.SourcesDirectory)/$(SOURCES_DIR_TRAIN)/conda_dependencies.yml'
    imageName: $(MODEL_NAME).$(get_model.MODEL_VERSION)
    workingDirectory: ${{ parameters.workingDirectory }}
