# Continuous Integration (CI) pipeline that orchestrates the training, evaluation, and registration of the model.
parameters:
  - name: aml_pipeline_name
    displayName: AML Pipeline Name to trigger
    type: string
    default: nonpython-data-processing-pipeline
  - name: workingDirectory
    displayName: Working Directory for sample
    type: string
    default: samples/non-python-preprocess

resources:
  containers:
  - container: mlops
    image: mlopsmanufacturing/build-agent/nonpython:latest
    endpoint: mlopsmanufacturingacr

pr: none

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - samples/non-python-preprocess/ml_model/preprocess/Dockerfile
    - samples/non-python-preprocess/ml_model/preprocess/preprocess_os_cmd_aml.py
    - samples/non-python-preprocess/ml_service/pipelines/build_data_processing_os_cmd_pipeline.py
    - samples/non-python-preprocess/devops_pipelines/03-custom-process-data-os-cmd.yml
    - samples/non-python-preprocess/devops_pipelines/variables-template.yml
    - samples/non-python-preprocess/devops_pipelines/code-quality-template.yml
    - samples/non-python-preprocess/devops_pipelines/trigger-preprocessing-pipeline.yml


variables:
- template: variables-template.yml
- group: nonpython-preprocess-aml-vg

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Data_CI'
  displayName: 'Data code quality and publish preprocessing pipeline'
  jobs:
  - job: "Data_CI_Pipeline"
    displayName: "Data CI Pipeline"
    container: mlops
    timeoutInMinutes: 0
    steps:
    - template: code-quality-template.yml
      parameters:
        workingDirectory: ${{ parameters.workingDirectory }}
    - task: AzureCLI@1
      enabled: true
      inputs:
        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
        scriptLocation: inlineScript
        workingDirectory: ${{ parameters.workingDirectory }}
        inlineScript: |
          set -e # fail on error
          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          # Invoke the Python building and publishing a data preprocessing pipeline
          python -m ml_service.pipelines.build_data_processing_os_cmd_pipeline
      displayName: 'Publish Data Preprocessing OS cmd Pipeline'

# Trigger_Preprocessing_Pipeline
- template: trigger-preprocessing-pipeline.yml
  parameters:
    # Template parameters can not be expanded, hard coded here
    aml_pipeline_name: ${{ parameters.aml_pipeline_name }}
    workingDirectory: ${{ parameters.workingDirectory }}
    # aml_pipeline_name: ${{ variable.PREPROCESSING_OS_CMD_PIPELINE_NAME }}
    # aml_pipeline_name: $(PREPROCESSING_OS_CMD_PIPELINE_NAME)
    # Variable expanding for Parameters is not always possible:
    # https://developercommunity.visualstudio.com/content/problem/429990/azure-pipelines-passing-a-variable-as-a-parameter.html