trigger:
  branches:
    include:
    - main
  paths:
    include:
    - samples/yesno/ml_model
    - samples/yesno/ml_service

variables:
- template: yesno-variables-template.yml
- group: iac-aml-vg

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Model_CI'
  displayName: 'Model CI'
  jobs:
  - job: "Model_CI_Pipeline"
    displayName: "Model CI Pipeline"
    timeoutInMinutes: 0
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
    - bash: |
        python -m pip install --upgrade pip setuptools wheel
      displayName: 'Install tools'
    - bash: |
        pip install -r samples/yesno/devops_pipelines/requirements.txt --use-deprecated=legacy-resolver
        pip install --upgrade azureml-sdk
      displayName: pip install
    - template: code-quality-template.yml
    - task: AzureKeyVault@1
      displayName: Azure Key Vault
      inputs:
        azureSubscription: '$(AZURE_RM_SVC_CONNECTION)'
        keyVaultName: '$(KEYVAULT_NAME)'
        secretsFilter: aml-storage-account-key,acr-password
        runAsPreJob: false
    - task: AzureCLI@1
      env:
        AML_STORAGE_ACCOUNT_KEY: $(aml-storage-account-key)
        ACR_PASSWORD: $(acr-password)
      inputs:
        azureSubscription: '$(AZURE_RM_SVC_CONNECTION)'
        scriptLocation: inlineScript
        workingDirectory: $(Build.SourcesDirectory)
        inlineScript: |
          set -e # fail on error
          # Invoke the Python building and publishing a training pipeline
          cd samples/yesno
          python -m ml_service.pipelines.build_pipeline
      displayName: 'Publish Azure Machine Learning Pipeline'