trigger: none

pool:
  vmImage: 'ubuntu-20.04'

variables:
- name: workingDir
  value: edge
- name: pythonVersion
  value: '3.7'
- template: ${{variables['System.DefaultWorkingDirectory']}}/.pipelines/variables/vars-dev.yml
- name: image_tag
  value: $(build.BuildId)

jobs:
- job: iot_module_validation
  displayName: Run IoT Edge Module validation
  steps:
  - template: ${{variables['System.DefaultWorkingDirectory']}}/.pipelines/templates/python-code-validation.yml
    parameters:
      workingDir: $(workingDir)
      pythonVersion: $(pythonVersion)

  - template: ${{variables['System.DefaultWorkingDirectory']}}/.pipelines/templates/iot-build-modules.yml
