# Pipeline that builds and pushes the build-agent image.
parameters:
  - name: workingDirectory
    displayName: Working Directory for sample
    type: string
    default: samples/image-classification-tensorflow

resources:
- repo: self

pool: 
  vmImage: 'ubuntu-latest'

pr:
  branches:
    include:
    - main
  paths:
    include:
    - samples/image-classification-tensorflow/devops_pipelines/build_agent/Dockerfile
    - samples/image-classification-tensorflow/devops_pipelines/build_agent/ci_dependencies.yml

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - samples/image-classification-tensorflow/devops_pipelines/build_agent/Dockerfile
    - samples/image-classification-tensorflow/devops_pipelines/build_agent/ci_dependencies.yml

variables:
- name: containerRegistry
  value: mlopsmanufacturingacr
- name: imageName
  value: mlopsmanufacturing/build-agent/tensorflow
        
steps:
  - task: Docker@2
    displayName: Build and Push
    inputs:
      command: buildAndPush
      containerRegistry: '$(containerRegistry)'
      repository: '$(imageName)'
      tags: |
       ${{format('build-{0}', '$(Build.BuildNumber)')}}
       latest
      buildContext: '${{ parameters.workingDirectory }}' 
      dockerFile: '${{ parameters.workingDirectory }}/devops_pipelines/build_agent/Dockerfile