trigger:
  branches:
    include:
    - main
    - release
  paths:
    include:
    - docs/*
    - README.md
    - .pipelines/ci/docs.yml
    - .pipelines/templates/docs-validation.yml

pool:
  vmImage: 'ubuntu-20.04'

jobs:
- job: docs_validation
  displayName: 'Run docs validation tests'
  steps:
  - template: ${{variables['System.DefaultWorkingDirectory']}}/.pipelines/templates/docs-validation.yml
