# Continuous Integration (CI) pipeline that orchestrates the training, evaluation, and registration of the model.

resources:
  containers:
  - container: mlops
    image: mlopsmanufacturing/build-agent/tensorflow:latest
    endpoint: mlopsmanufacturingacr

pr: none
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - ml_model/preprocessing/
    - ml_model/parameters.json
    - ml_service/pipelines/build_data_processing_pipeline.py
    - .pipelines/02-processing-data.yml
    - .pipelines/variables-template.yml
    - .pipelines/code-quality-template.yml
    - .pipelines/trigger-preprocessing-pipeline.yml


variables:
- template: variables-template.yml
- group: devopsforai-aml-vg

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Data_CI'
  displayName: 'Data code quality and publish preprocessing pipeline'
  jobs:
  - job: "Data_CI_Pipeline"
    displayName: "Data CI Pipeline"
    container: mlops
    timeoutInMinutes: 0
    steps:
    - template: code-quality-template.yml
    - task: AzureCLI@1
      enabled: true
      inputs:
        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
        scriptLocation: inlineScript
        workingDirectory: $(Build.SourcesDirectory)
        inlineScript: |
          set -e # fail on error
          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          # Invoke the Python building and publishing a data preprocessing pipeline
          python -m ml_service.pipelines.build_data_processing_pipeline
      displayName: 'Publish Data Preprocessing Pipeline'
      env:
        APP_INSIGHTS_CONNECTION_STRING: $(APP_INSIGHTS_CONNECTION_STRING)

# Trigger_Preprocessing_Pipeline
- template: trigger-preprocessing-pipeline.yml
  parameters:
    # Template parameters can not be expanded, hard coded here
    aml_pipeline_name: 'flower-preprocessing-pipeline'
    # aml_pipeline_name: ${{ variable.PREPROCESSING_PIPELINE_NAME }}
    # aml_pipeline_name: $(PREPROCESSING_PIPELINE_NAME)
    # Variable expanding for Parameters is not always possible:
    # https://developercommunity.visualstudio.com/content/problem/429990/azure-pipelines-passing-a-variable-as-a-parameter.html