# Pipeline that builds and pushes the microsoft/mlopspython image.
resources:
- repo: self

pool: 
  vmImage: 'ubuntu-latest'

pr: none
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - environment_setup/Dockerfile
    - ml_model/ci_dependencies.yml

variables:
- group: devopsforai-aml-vg
        
steps:
  - task: Docker@2
    displayName: Build and Push
    inputs:
      command: buildAndPush
      containerRegistry: '$(ACR_SVC_CONNECTION)'
      repository: 'public/mlops/tensorflow'
      tags: |
       ${{format('build-{0}', '$(Build.BuildNumber)')}}
       latest
      buildContext: '$(Build.SourcesDirectory)' 
      dockerFile: '$(Build.SourcesDirectory)/environment_setup/Dockerfile'
