# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for managed runs. These include runs against
# the localdocker, remotedocker, and cluster compute targets.

name: nonpythonpreprocess_env
dependencies:
  # The python interpreter version.
  # Currently Azure ML Workbench only supports 3.5.2 and later.
  - python=3.7.*
  - joblib=0.16.*
  - pillow=7.2.*
  - pip=20.0.*

  - pip:
      # Base AzureML SDK
      - azureml-sdk==1.13.*
      - azureml-contrib-services==1.13.*

      # Minimum required for the scoring environment. Must match AzureML SDK version.
      # https://docs.microsoft.com/en-us/azure/machine-learning/concept-environments
      - azureml-defaults==1.13.*

